### ISSUE TITLE
error when invoking ./waf configure

### ISSUE THREAD

**Issue by lokkiikkol** [drobilla/ingen#11]
hi there i get:

Traceback (most recent call last):
  File "./waf", line 5, in <module>
    from waflib import Context, Scripting
ImportError: No module named waflib

when i try ./waf configure

i downloaded as zip file from github

**Comment by ENPark** [comment]
Same here, the folder waflib doesn't get cloned with git or downloaded in the zip file. I tried to replace with waflib from https://gitlab.com/ita1024/waf/-/tree/master, without sucess.
This is the result of that particular operation:

Traceback (most recent call last):
  File "/home/niklas3/ingen/waflib/Scripting.py", line 141, in waf_entry_point
    set_main_module(wscript)
  File "/home/niklas3/ingen/waflib/Scripting.py", line 191, in set_main_module
    Context.g_module = Context.load_module(file_path)
  File "/home/niklas3/ingen/waflib/Context.py", line 682, in load_module
    exec(compile(code, path, 'exec'), module.__dict__)
  File "/home/niklas3/ingen/wscript", line 6, in <module>
    from waflib.extras import autowaf
ImportError: cannot import name autowaf

**Comment by lokkiikkol** [comment]
yep, i tried the same with the same results. look here: https://github.com/drobilla/ingen/issues/9 and let me know if you get somewhere, i am not at my pc a.t.m

**Comment by drobilla** [comment]
waflib is a submodule, you need to run `git submodule update --init` after cloning as usual:

```
git clone https://github.com/drobilla/ingen.git
cd ingen
git submodule update --init --recursive
./waf configure
```

I don't know how Github deals with submodules in zip files, sorry.

**Comment by drobilla** [comment]
I added some code to the wrapper script to avoid this confusion a while ago, but forgot to update the one in ingen: https://github.com/drobilla/ingen/commit/96840d3fc46ec6531a3c5b53eee1c0713723f9a7
