### ISSUE TITLE
DSP usage indicator inaccurate

### ISSUE THREAD

**Issue by loki42** [drobilla/ingen#14]
![ingen_dsp](https://user-images.githubusercontent.com/1124356/75317602-882d7d80-58bc-11ea-88ed-f85727d5c7bd.png)

The DSP usage indicator is showing 270%  where as HTOP is showing 3.3% for one ingen thread, 2.7% for another and 0.7% for the third. 

Tested on Intel X86_64 and ARM AArch64 with similar behaviour.

**Comment by drobilla** [comment]
It's a DSP usage meter, not a CPU usage meter, so they don't necessarily correlate much.

That said, it certainly shouldn't be 270% if things are working (not dropping out constantly).  Can you send me the graph?

**Comment by loki42** [comment]
I think this might have been something to do with having debugging turned on the client side (ingen was run with -gd) I'll see if I can reproduce it again on Intel.

**Comment by drobilla** [comment]
Didn't turn out to be an issue?

**Comment by loki42** [comment]
Fixed when I updated the parsing code so I think it was at my end.
