### ISSUE TITLE
ingen doesn't allow setting broadcast on a port

### ISSUE THREAD

**Issue by loki42** [drobilla/ingen#18]
The docs suggest: 

Property ingen:broadcast
broadcast
Whether or not the port's value or activity should be broadcast to clients.

However when setting this on a port, either with a put or set:

ingen.set("/main/ratio/numerator", "http://drobilla.net/ns/ingen#broadcast", True)

ingen.put("/main/ratio/numerator", "http://drobilla.net/ns/ingen#broadcast true")

The server repeats error: (socket):6:5: bad subject until I kill it. Is there a way to get an output ports current value any other way?

**Comment by drobilla** [comment]
> ingen.set("/main/ratio/numerator", "http://drobilla.net/ns/ingen#broadcast", True)

Python booleans aren't supported like this.  I guess you just never encountered bools before (decimal numbers coincidentally work because the bindings just stringify whatever, but "True" is not valid Turtle).

> ingen.put("/main/ratio/numerator", "http://drobilla.net/ns/ingen#broadcast true")

Also invalid Turtle, predicate URI isn't quoted.

```
#!/usr/bin/env python

import ingen

s = ingen.Remote('unix:///tmp/ingen.sock')

s.put('/main/plug', 'a ingen:Block; lv2:prototype <http://drobilla.net/plugins/mda/TestTone>')
s.set("/main/plug/left_out", "http://drobilla.net/ns/ingen#broadcast", "true")
```

**Comment by drobilla** [comment]
FYI I've gone ahead with writing proper Python bindings for serd, so the medium term plan here is to use those and actually have a decent API for dealing with this data.  Will have to switch to the new major version for that to happen though, so you'll have to suffer under the stringly typed API for now.
