### ISSUE TITLE
JSON / JSON-LD serialisation

### ISSUE THREAD

**Issue by loki42** [drobilla/ingen#19]
Would you be open to a pull request that add an additional serialisation format for network communication? Maybe the client can negotiate one? RDF / turtle is slow and difficult to process in many languages for getting out simple info. Encoding it in JSON or JSON-LD seems to make it much easier for basically all languages to parse very quickly as JSON is a very well supported format.

**Comment by drobilla** [comment]
Or: `rdflib` sucks :)

In theory, sure, but much easier said than done.  I don't think a bespoke serialization (that isn't a general RDF one) really makes much sense for Ingen, but JSON-LD would certainly be a nice best-of-both-worlds.  There is a serd branch for that I was working on, but it's quite complex and I haven't gotten it into a usable state yet.

**Comment by loki42** [comment]
The main use case for me is for output CV port value updates.  I'm making a
few generative lv2 modules and being able to see signal follow would be
handy but the current system has a ton of over head with slow parsing and a
lot of extra info for one float. Also the other bug with enabling broadcast
is related to that.  If there's a better approach to getting values at a
sensible rate for animation (maybe a few a second) I'd love to know.

**Comment by drobilla** [comment]
I see.  I idly considered adding other facilities if just doing everything in the same uniform way ever proved too slow, but at least with the main implementation that hasn't proved the case.  I can see how rdflib would dramatically change that equation though.

There could be some mechanism to request particular updates on a different "channel" (socket) which would be handled differently.  If you really want speed, it could even use the binary protocol (with all the platform caveats thereof).  I'm not really sure how this would look though.

**Comment by loki42** [comment]
That does sound good.  If you see the other bug I can't get publish to work
for a single port which might help.

**Comment by drobilla** [comment]
I don't get how you can have both this problem and one that means you can't make this situation happen in the first place?

**Comment by drobilla** [comment]
So after some (sidetracked, sorry) tinkering wondering about the long run here: https://github.com/drobilla/serd/commit/9c284e1970d4953f1f1fa415809b389ea5b96251

Which makes me wonder if providing a proper interface and getting rid of this string mess would really be so much work.  Not pure Python, of course, but, meh.

**Comment by loki42** [comment]
Oh I can turn on broadcast for all ports just not a specific one.  :-)

**Comment by drobilla** [comment]
Huh.  I'll look into it this weekend.

I guess some deeper fix for garbage syntax on the server side will be needed.  Maybe skip until a "." is read or something...

**Comment by loki42** [comment]
It's very easy to crash the server side with invalid commands.

**Comment by drobilla** [comment]
Yeah, it's pretty resilient at the semantic level so to speak (all the events handle all the edge cases and fail gracefully and such), but actually invalid syntax isn't handled so well.  It's a bit tricky because the parser is pulling directly from the socket, but I'll figure something out.

**Comment by loki42** [comment]
#18 has examples but basically: 

ingen.set("/main/ratio/numerator", "http://drobilla.net/ns/ingen#broadcast", True)
ingen.put("/main/ratio/numerator", "http://drobilla.net/ns/ingen#broadcast true")

are the problem cases for me.

**Comment by drobilla** [comment]
I suppose I should mention, in case its not obvious, that the Python bindings are just a one-off hack to make ingenish kinda work.  They're pretty sketchy, as you've seen, and the server is not really hardened for clients that talk syntactic nonsense (though it should be, as any server should in general).

Turtle fragments in the API as above especially need to go.  You might want to consider improving them a bit, this can be done just in Python land and is about a billion times easier than implementing JSON or something like that (and works towards it anyway, since the API would also have to change to be Pythonic and not have Turtle strings and stuff in it for that to work).
