### ISSUE TITLE
Ingen adds a DC offset vs same plugin run in Jalv

### ISSUE THREAD

**Issue by loki42** [drobilla/ingen#22]
![dc-offset](https://user-images.githubusercontent.com/1124356/108007297-b66a1700-7051-11eb-9039-da27df6b7f52.jpg)

Green is Ingen purple is Jalv in photo.  Ingen appears to be offset by approximately 0.7 in the -1 to 1 range. I've tried different plugins and offset is the same with ones tested so far. I can correct the offset with a difference module. I can add cursors for more precise measurement if needed, but probably easier to measure in a jack based oscilloscope.

**Comment by drobilla** [comment]
Huh.  That's... weird.  Ingen isn't much in the business of doing anything with signals itself.

Got the graph?

**Comment by loki42** [comment]
I'll make a simple one now, basically any plugin I've tested does the same
with just it connected to the output. I was surprised.

**Comment by drobilla** [comment]
Okay, I can try then.

> I was surprised.

Me too...

**Comment by loki42** [comment]
![20210217_003314](https://user-images.githubusercontent.com/1124356/108071500-e77e3200-70b9-11eb-895c-f9caa72d6d0d.jpg)
![20210217_003433](https://user-images.githubusercontent.com/1124356/108071505-e947f580-70b9-11eb-8bbe-d55bdc9d7a9e.jpg)

I think something else was happening yesterday as I can't reproduce the same level of offset. Here's the same signal out of both outputs in jalv, then the jalv signal out 1 out and the Ingen signal out the other. This appears to just be a bit of level difference so I think the issue yesterday might have been hardware specific.

**Comment by drobilla** [comment]
That would be a lot less surprising.  I'll see if everything is sane in the digital domain, at least.

Alas, my device is still in a box somewhere, so I can't check that.  Greetings from Canada, eh? :)

**Comment by loki42** [comment]
Good to hear you got there!  This is testing Hector the eurorack version as
I need to get v Oct CV signals in / out accurately.  Beebo isn't DC
coupled.
