### ISSUE TITLE
MIDI learn bindings ignore channel

### ISSUE THREAD

**Issue by loki42** [drobilla/ingen#25]
When you learn a CC, it appears to not encode the channel, just the CC and it responds to all channels.

**Comment by loki42** [comment]
give me a yell if you're working to fix the omni CC issue, otherwise I'll look into it and send a pull request when it's done.

**Comment by drobilla** [comment]
Currently have some time at last and am dragging myself out of a _deep_ hole of long-unmaintained quasi-rotten things to get Ingen moving forward again, but I'll try to get there as soon as possible.

**Comment by drobilla** [comment]
Fixed in 96be7732
