### ISSUE TITLE
Seg fault on deleting node

### ISSUE THREAD

**Issue by loki42** [drobilla/ingen#26]
reproducible with the latest code, running on x86_64. 

result: Seg fault
Steps to reproduce, load attached patch, 
click on sub 2 then delete node loop_common_in_1.

The patch uses no LV2 modules, only builtins.
[delete_crash.ingen.tar.gz](https://github.com/drobilla/ingen/files/6241399/delete_crash.ingen.tar.gz)

Cheers
Loki

**Comment by drobilla** [comment]
Fixed in fef4ce2b
