### ISSUE TITLE
Python bindings hang due to missing null terminator

### ISSUE THREAD

**Issue by loki42** [drobilla/ingen#5]
When querying Ingen over a socket with both server and client on X86, a get command in Ingenish does not complete as a final null terminator isn't seen. 

This occurs on ARM and X86, over remote and localhost socket connections. Tested on Debian and Ubuntu.

**Comment by loki42** [comment]
This is the command i'm attempting 
set /main/Delay/l_delay ingen:value 0.2

**Comment by drobilla** [comment]
Fixed by dc0548bc
