### ISSUE TITLE
connect ingen to midi

### ISSUE THREAD

**Issue by han-so1omon** [drobilla/ingen#7]
how to connect ingen to midi thru qjackctl? it seems that a midi device such as vmpk:out is not compatible with ingen:control or ingen:event.

**Comment by han-so1omon** [comment]
In patchage they show up as `midi` vs `alsa midi`

**Comment by han-so1omon** [comment]
It seems to work with cadence/catia

**Comment by drobilla** [comment]
Ingen uses Jack MIDI.  You can run Jack in such a way that it exposes Jack MIDI to ALSA, or use an external tool like a2jmidid.
